name:           cabal2obs
version:        "0"
synopsis:       Convert a set of Cabal files into an OBS project
description:    Convert a set of Cabal files into an OBS project.
maintainer:     opensuse-haskell@opensuse.org
license:        GPL-3
license-file:   LICENSE
github:         opensuse-haskell/cabal2obs
category:       Distribution
tested-with:    GHC > 7.10 && < 8.1
author:
 - Peter Simons
 - Bryan O'Sullivan
 - Jens Petersen

ghc-options:            -Wall

executables:
  cabal2obs:
    main:               Main.hs
    dependencies:
      - base < 5
      - Cabal > 1.24
      - directory
      - filepath
      - shake
      - spdx
      - time
    ghc-options:        -threaded -with-rtsopts=-qg -with-rtsopts=-qb
    other-modules:
      - Cabal2Spec
      - Oracle
      - Oracle.Compiler
      - Oracle.FlagAssignment
      - Oracle.ForcedExecutables
      - Oracle.Hackage
      - Oracle.PackageList
      - Orphans
      - ParseUtils
      - Types
