name:           cabal2obs
version:        "0"
synopsis:       Convert a set of Cabal files into an OBS project
description:    Convert a set of Cabal files into an OBS project.
maintainer:     opensuse-haskell@opensuse.org
license:        GPL-3
license-file:   LICENSE
github:         opensuse-haskell/cabal2obs
category:       Distribution
tested-with:    GHC > 7.10 && < 8.3
author:
 - Peter Simons
 - Bryan O'Sullivan
 - Jens Petersen

ghc-options:            -Wall

executables:
  cabal2obs:
    main:               Main.hs
    dependencies:
      - base < 5
      - Cabal > 2
      - containers
      - directory
      - filepath
      - shake >= 0.16
      - spdx
      - time
    ghc-options:        -threaded -with-rtsopts=-qg -with-rtsopts=-qb
    other-modules:
      - Cabal2Spec
      - Config
      - Config.LTS8
      - Config.LTS8.Stackage
      - Config.LTS9
      - Config.LTS9.Stackage
      - Config.LTS10
      - Config.LTS10.Stackage
      - Config.Nightly
      - Config.Nightly.Stackage
      - Oracle
      - Oracle.Compiler
      - Oracle.FlagAssignment
      - Oracle.ForcedExecutables
      - Oracle.Hackage
      - Oracle.PackageList
      - Orphans
      - ParseStackageConfig
      - ParseUtils
      - Types
    other-extensions:
      - CPP
      - DeriveAnyClass
      - DeriveGeneric
      - GeneralizedNewtypeDeriving
      - OverloadedStrings
      - TypeFamilies
