# .hlint.yaml

# Specify additional command line arguments
- arguments: [ --threads ]

# Control which extensions/flags/modules/functions can be used
- extensions:
  - default: false
  - name:
      - ApplicativeDo
      - DeriveAnyClass
      - DeriveGeneric
      - NoImplicitPrelude
      - OverloadedLists
      - OverloadedStrings
      - RecordWildCards
      - TypeFamilies
  - { name: FlexibleInstances, within: [Orphans, Oracle.Hackage] }

- flags:
  - { name: -fno-warn-orphans, within: [Orphans] }

# - modules:
#   - {name: [Data.Set, Data.HashSet], as: Set} # if you import Data.Set qualified, it must be as 'Set'
#   - {name: Control.Arrow, within: []} # Certain modules are banned entirely
#
# - functions:
#   - {name: unsafePerformIO, within: []} # unsafePerformIO can only appear in no modules

# Add custom hints for this project
#
# Will suggest replacing "wibbleMany [myvar]" with "wibbleOne myvar"
# - error: {lhs: "wibbleMany [x]", rhs: wibbleOne x}

# Turn on hints that are off by default
- warn: { name: Use explicit module export list }
- group: { name: generalise, enabled: false }

# Ignore some builtin hints
# - ignore: {name: Use let}
# - ignore: {name: Use const, within: SpecialModule} # Only within certain modules

# Define some custom infix operators
# - fixity: infixr 3 ~^#^~
