# .travis.yml

language: c
sudo: false

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.24
      - ghc-8.0.1

before_install:
 - unset CC
 - export PATH=$HOME/.cabal/bin:/opt/ghc/8.0.1/bin:/opt/cabal/1.24/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update -v
 - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
 - cabal install hpack shake

script:
  - make
