# .travis.yml

language: c
sudo: false

cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/build/opensuse-haskell/configuration/_build

addons:
  apt:
    sources:
      - hvr-ghc
      - deadsnakes
    packages:
      - cabal-install-1.24
      - ghc-8.0.2
      - python3.5
      - rpm

before_install:
 - unset CC
 - export PATH=$HOME/.local/bin:$HOME/.cabal/bin:/opt/ghc/bin:/opt/cabal/bin:$PATH
 - mkdir -p $HOME/.local/bin
 - ln -s $(type -p python3.5) $HOME/.local/bin/python3

install:
 - python3 --version
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update -v
 - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
 - (cd tools/cabal2obs && cabal new-build)

script:
  - tools/cabal2obs/dist-newstyle/build/cabal2obs-0/build/cabal2obs/cabal2obs --digest --keep-going --no-progress
