name:                   cabal2obs
version:                "20160630"
synopsis:               Convert a set of Cabal files into an OBS project
description:            Convert a set of Cabal files into an OBS project.
maintainer:             opensuse-haskell@opensuse.org
license:                GPL-3
license-file:           LICENSE
github:                 opensuse-haskell/cabal2obs
category:               Distribution
tested-with:            GHC > 7.10 && < 8.1

ghc-options:            -Wall

executables:
  generate:
    main:               Main.hs
    dependencies:       base < 5, hackage-db, Cabal
